### PR TITLE
[App-463] preload errors leaked to renderer

### PR DESCRIPTION
**Pull request by alexstrat**
Following https://github.com/getstation/electron-chrome-extension/pull/47#discussion_r294635374 removed the unnecessary and broken polyfill for `postMessage`.

(broken: `messageObj` is already defined)

Remove some useless logs as well.

Fix a broken condition that leaked a `window.opener` in the renderer.

### CODE REVIEW

**Comment by alexstrat** [comment]
Published as of d466133db8af181d58829a9570931081a9eecfe0 as `electron-chrome-extension@3.0.1-rc`

**Comment by alexstrat** [comment]
Published as of ff1032ea0cf7b0c01b96b8cb7ad7d2e22d83319b as `electron-chrome-extension@3.0.1-rc.2`

**Comment by hugomano** [comment]
- [x] Mixmax
- [x] Clearbit
- [x] Gmelius
- [x] Mailtracker
- [x] Boomerang

**Comment by hugomano** [comment]
LGTM!

**Pull request merged**
